FROM default-route-openshift-image-registry.apps.ocpdevgra.dti.co.id/openshift/nodejs:16-ubi8
WORKDIR /app
COPY ./package.json ./package.json
COPY ./public ./public
COPY ./src ./src
RUN yarn install
EXPOSE 3000

CMD ["yarn","start"]
